name: OSV Scan
on:
  pull_request:
  push:
    branches: ['main']
permissions:
  contents: read
jobs:
  osv:
    runs-on: [self-hosted, linux, x64, docker]
    steps:
      - uses: actions/checkout@v6
      - uses: google/osv-scanner-action@v1
        with:
          scan-args: -r .
